name: gh-pages

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.prepare_tag.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3

        # This adds the docs to gh-pages-build/doc
      - name: Build the doc
        run: |
          cargo doc --no-deps --all-features
          mkdir -p gh-pages-build
          cp -r target/doc gh-pages-build/doc
          echo "<meta http-equiv=refresh content=0;url=pyo3_asyncio/index.html>" > gh-pages-build/doc/index.html

      - name: Prepare tag
        id: prepare_tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          echo "::set-output name=tag_name::${TAG_NAME}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-build/
          destination_dir: ${{ steps.prepare_tag.outputs.tag_name }}
          full_commit_message: "Upload documentation for ${{ steps.prepare_tag.outputs.tag_name }}"

  release:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Create latest tag redirect
        env:
          TAG_NAME: ${{ needs.deploy.outputs.tag_name }}
        run: |
          mkdir public
          echo "<meta http-equiv=refresh content=0;url='$TAG_NAME/'>" > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          full_commit_message: "Release ${{ needs.deploy.outputs.tag_name }}"
          keep_files: true
